# Generated by Django 4.0 on 2022-09-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_to_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestable',
            name='course_id',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='coursestable',
            name='skillsets',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
