# Generated by Django 4.0 on 2022-09-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_to_jobs', '0002_coursestable_course_id_coursestable_skillsets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestable',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='coursestable',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='coursestable',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coursestable',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='coursestable',
            name='skillsets',
        ),
        migrations.AddField(
            model_name='coursestable',
            name='jobs',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
