# Generated by Django 4.0 on 2022-09-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_to_jobs', '0003_remove_coursestable_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestable',
            name='courseskills',
            field=models.CharField(default='0000000', max_length=1000),
        ),
        migrations.AddField(
            model_name='coursestable',
            name='jobskills',
            field=models.CharField(default='0000000', max_length=1000),
        ),
        migrations.AddField(
            model_name='coursestable',
            name='similarity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coursestable',
            name='course',
            field=models.CharField(default='0000000', max_length=200),
        ),
        migrations.AlterField(
            model_name='coursestable',
            name='jobs',
            field=models.CharField(default='0000000', max_length=200),
        ),
    ]
